### ISSUE TITLE
可以扩展支持ERNIE-Bot-4模型以及system角色设置吗？

### ISSUE THREAD

**Issue by JJYY2333** [anhao/go-ernie#3]
目前使用发现的问题：
1. 不支持ERNIE-Bot-4模型；
2. system参数无法设置（即设置系统角色个性信息，api接口已有）

**Comment by anhao** [comment]
ERNIE-Bot-4 已经支持了的， 你可以看下这个 test  https://github.com/anhao/go-ernie/blob/main/ernie_bot_4_test.go

system 我晚上看一下

**Comment by anhao** [comment]
已更新 https://github.com/anhao/go-ernie/releases/tag/v1.0.6
