### ISSUE TITLE
AccessToken刷新问题

### ISSUE THREAD

**Issue by WhiteNightMo** [anhao/go-ernie#4]
大佬，感谢分享，包很好用。
我目前在使用过程中遇到了一个问题，请大佬帮忙看看。就是目前好像不支持手动/自动刷新AccessToken，因为config和accessToken都是小写的，无法自行获取后覆盖，是否考虑支持一下~
```go
func (c *Client) newRequest(ctx context.Context, method, url string, setters ...requestOption) (*http.Request, error) {
	// Default Options
	args := &requestOptions{
		body:   nil,
		header: make(http.Header),
	}
	for _, setter := range setters {
		setter(args)
	}
	req, err := c.requestBuilder.Build(ctx, method, url, args.body, args.header)
	if err != nil {
		return nil, err
	}
	if len(c.config.accessToken) == 0 {
		accessToken, err := c.GetAccessToken(ctx)
		if err != nil {
			return nil, err
		}
		c.config.accessToken = *accessToken
	}

	c.setCommonQuery(req)
	return req, nil
}
```

**Comment by anhao** [comment]
是的，目前没做自动刷新的功能，只能自己控制 accessToken ,然后初始化 client 

通过 appid  和 secret 方式初始化会自动获取 accessToken

**Comment by WhiteNightMo** [comment]
哈哈哈，是这样的大佬，我是想着在项目启动的时候初始化好client，后续直接调用相关对话方法就好，但这就产生了一个问题，因为AccessToken有效期是30天，如果在这期间没有重启的话，项目就挂了。
我先开个协程去刷吧，期待大佬早日支持~

**Comment by anhao** [comment]
> 哈哈哈，是这样的大佬，我是想着在项目启动的时候初始化好client，后续直接调用相关对话方法就好，但这就产生了一个问题，因为AccessToken有效期是30天，如果在这期间没有重启的话，项目就挂了。 我先开个协程去刷吧，期待大佬早日支持~

可以的，预计下个版本支持自动刷新

**Comment by anhao** [comment]
[v1.0.7](https://github.com/anhao/go-ernie/releases/tag/v1.0.7) 版本已支持

**Comment by WhiteNightMo** [comment]
> [v1.0.7](https://github.com/anhao/go-ernie/releases/tag/v1.0.7) 版本已支持

大佬，我看了下更新内容，目前`GetAccessToken`函数内部是已经实现了自动刷新和缓存accessToken，但是`c.config.accessToken`好像并不会随着accessToken刷新而更新哎。
```go
func (c *Client) newRequest(ctx context.Context, method, url string, setters ...requestOption) (*http.Request, error) {
	// Default Options
	args := &requestOptions{
		body:   nil,
		header: make(http.Header),
	}
	for _, setter := range setters {
		setter(args)
	}
	req, err := c.requestBuilder.Build(ctx, method, url, args.body, args.header)
	if err != nil {
		return nil, err
	}
	if len(c.config.accessToken) == 0 {
		accessToken, err := c.GetAccessToken(ctx)
		if err != nil {
			return nil, err
		}
		c.config.accessToken = *accessToken
	}

	c.setCommonQuery(req)
	return req, nil
}
```

**Comment by anhao** [comment]
> > [v1.0.7](https://github.com/anhao/go-ernie/releases/tag/v1.0.7) 版本已支持
> 
> 大佬，我看了下更新内容，目前`GetAccessToken`函数内部是已经实现了自动刷新和缓存accessToken，但是`c.config.accessToken`好像并不会随着accessToken刷新而更新哎。
> 
> ```go
> func (c *Client) newRequest(ctx context.Context, method, url string, setters ...requestOption) (*http.Request, error) {
> 	// Default Options
> 	args := &requestOptions{
> 		body:   nil,
> 		header: make(http.Header),
> 	}
> 	for _, setter := range setters {
> 		setter(args)
> 	}
> 	req, err := c.requestBuilder.Build(ctx, method, url, args.body, args.header)
> 	if err != nil {
> 		return nil, err
> 	}
> 	if len(c.config.accessToken) == 0 {
> 		accessToken, err := c.GetAccessToken(ctx)
> 		if err != nil {
> 			return nil, err
> 		}
> 		c.config.accessToken = *accessToken
> 	}
> 
> 	c.setCommonQuery(req)
> 	return req, nil
> }
> ```

确实是的

**Comment by WhiteNightMo** [comment]
哈哈哈，大佬深夜迭代辛苦了，等周末有空了再好好考虑下这块吧:)

**Comment by anhao** [comment]
[V1.0.8](https://github.com/anhao/go-ernie/releases/tag/v1.0.8)

**Comment by WhiteNightMo** [comment]
收到，大佬辛苦
