### ISSUE TITLE
最新函数特性的支持有问题

### ISSUE THREAD

**Issue by mrold** [anhao/go-ernie#5]
### 消息结构体缺少 `name` 和 `function_call`字段
```
type ChatCompletionMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}
```
需要添加 `name` 和 `function_call`字段，否则接口会因缺少参数而失败。

### 官方请求参数demo

<img width="868" alt="image" src="https://github.com/anhao/go-ernie/assets/9475864/f3244014-0783-4fae-9bec-243f7cd47d26">

**Comment by anhao** [comment]
好的，收到 ，这是最近更新的吧

**Comment by mrold** [comment]
> 好的，收到 ，这是最近更新的吧

是的，大佬多费心了

**Comment by anhao** [comment]
[v1.0.7](https://github.com/anhao/go-ernie/releases/tag/v1.0.7) 版本已支持

**Comment by mrold** [comment]
> [v1.0.7](https://github.com/anhao/go-ernie/releases/tag/v1.0.7) 版本已支持

FunctionCall应该设置成指针
```
type ChatCompletionMessage struct {
	Role         string             `json:"role"`
	Content      string             `json:"content"`
	Name         string             `json:"name,omitempty"`
	FunctionCall *ErnieFunctionCall `json:"function_call,omitempty"`
}
```
